about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("new/", views.new_post, name="new_post"),
    path("follow/", views.follow_index, name="follow_index"),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/<int:post_id>/", views.post_view, name="post_view"),
    path(
        "<str:username>/<int:post_id>/edit/",
        views.post_edit,
        name="post_edit"),

    path("<str:username>/<int:post_id>/comment/",
         views.add_comment,
         name="add_comment"),

    path("<str:username>/follow/", views.profile_follow, name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow, name="profile_unfollow"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    #  регистрация и авторизация
    path("auth/", include("django.contrib.auth.urls")),
    path("auth/", include("users.urls")),

    path("admin/", admin.site.urls),
    #  если нужного шаблона для /auth не нашлось в файле users.urls —
    #  ищем совпадения в файле django.contrib.auth.urls

    # импорт правил из приложения posts
    path("", include("posts.urls", namespace='posts')),
    # импорт правил из приложения admin
    path("admin/", admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/author_card.html
<div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        {{ post.author }}
                                    </div>
                                    <div class="h3 text-muted">
                                        {{ post.author.username }}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков:   {{ author.follower.count }}<br />
                                            Подписан:  {{ author.follower.count }}
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                {{ post.id }}
                                            </div>
                                    </li>
                            </ul>
    <li class="list-group-item">
    {% if following %}
    <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button">
            Отписаться
    </a>
    {% else %}
    <a class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button">
    Подписаться
    </a>
    {% endif %}
</li>
</div>

templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' author.username post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %} 

templates/includes/follow_buton.html
<li class="list-group-item">
    {% if following %}
    <a class="btn btn-lg btn-light"
            href="{% url 'profile_unfollow' profile.username %}" role="button">
            Отписаться
    </a>
    {% else %}
    <a class="btn btn-lg btn-primary"
            href="{% url 'profile_follow' profile.username %}" role="button">
    Подписаться
    </a>
    {% endif %}
</li>

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
        <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">О технологиях</a>
      </p>
  <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube</p>
</footer>

templates/includes/menu.html
{% if user.is_authenticated %}
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новая запись</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/includes/post_card.html
<div class="card mb-3 mt-1 shadow-sm">
                            <div class="card-body">
                                    <p class="card-text">

                                            <a href="{% url 'posts:post_view' author.username post.id %} "><strong class="d-block text-gray-dark">@{{ author.username }}</strong></a>
                                        {{ post.text }}
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group ">
                                                    <!-- Ссылка на страницу записи в атрибуте href-->
                                                    <a class="btn btn-sm text-muted" href="{% url 'posts:post_view' author.username post.id %} " role="button">запись</a>
                                                    <!-- Ссылка на редактирование, показывается только автору записи -->
                                                    <a class="btn btn-sm text-muted" href="{% url 'posts:post_edit' author.username post.id %}" role="button">Редактировать</a>
                                                <a class="btn btn-sm text-muted" href="{% url 'posts:add_comment' author.username post.id %}" role="button">Оставить комментарий</a>
                                            </div>

                                            <!-- Дата публикации  -->
                                            <small class="text-muted">{{ post.pub_date }}</small>
                                    </div>
                            </div>
    <div class="card mb-3 mt-1 shadow-sm">
</div>